= Mapping a message that contains both basic and JSON fields 
:page-aliases: cfgPulsarStringJson.adoc
:page-tag: pulsar-connector,dev,develop,pulsar,json

When the data format for the message key or value is JSON, the DataStax Apache Pulsar™ connector mapping can include individual fields in the JSON structure.

In the following example, the key is text field and the value is JSON.
The key is mapped to the name field and each of the JSON fields to a separate column in the table.

[cols="a,a"]
|===
|key|value

|APPLE| 
[source,no-highlight]
----
{"symbol":"APPL", "value":208, "exchange":"NASDAQ", "industry":"TECH", "ts":"2018-11-26T19:26:27.483"}
----

|EXXON MOBIL| 
[source,no-highlight]
----
{"symbol":"M",
"value":80,
"exchange":"NYSE",
"industry":"ENERGY",
"ts":"2018-11-26T19:26:27.483"}
----

|GENERAL MOTORS| 
[source,no-highlight]
---- 
{"symbol":"GM", "value":38, "exchange":"NYSE", "industry":"AUTO", "ts":"2018-11-26T19:26:27.483"}
----

|AT&T| 
[source,no-highlight]
----
{"symbol":"AT&T",
"value":33,
"exchange":"NYSE",
"industry":"TELECOM",
"ts":"2018-11-26T19:26:27.483"}
----

|FORD MOTOR| 
[source,no-highlight]
---- 
{"symbol":"F", "value":10, "exchange":"NYSE", "industry":"AUTO", "ts":"2018-11-26T19:26:27.483"} `
----
|===

NOTE: JSON records in Pulsar can also have a schema associated with them.

== Table requirements

Ensure the following when mapping fields to columns:

* Data in the Apache Pulsar™ field is compatible with the database table column link:http://docs.datastax.com/en/dse/6.8/cql/cql/cql_reference/refDataTypes.html[data type].
* Pulsar field mapped to a database primary key (PK) column always contains data.
Null values are not allowed in PK columns.

. Set up the xref:index.adoc#supported-databases[supported database] table.
. Create the keyspace.
Ensure that keyspace is replicated to a datacenter that is set in the DataStax Apache Pulsar Connector xref:reference-pulsar-dse-connection.adoc#contactPoints[contactPoints] parameter.
For example, create the `stocks_keyspace`:
+
[source,language-bash]
----
cqlsh -e "CREATE KEYSPACE stocks_keyspace \
  WITH replication = {'class': 'NetworkTopologyStrategy',\
  'Cassandra': 1};"
----
+
NOTE: The datacenter name is case sensitive.
Use link:https://docs.datastax.com/en/dse/6.8/dse-dev/datastax_enterprise/tools/nodetool/toolsRing.html[nodetool ring] to get a list of datacenters.

. Create the table. For example, create the `stocks_table`:
+
[source,language-bash]
----
cqlsh -e "CREATE TABLE stocks_keyspace.stocks_table ( \
  symbol text, \
  ts timestamp, \
  exchange text, \
  industry text, \
  name text, \
  value double, \
  PRIMARY KEY (symbol, ts));"
----

. Verify that all nodes have the same schema version using link:https://docs.datastax.com/en/dse/6.8/dse-admin/datastax_enterprise/tools/nodetool/toolsDescribeRing.html[nodetool describering]. Replace keyspace_name:
+
[source,language-bash]
----
nodetool describering -- keyspace\_name
----

. In the DataStax Connector configuration file:
..   Add the topic name to `topics`.
..   Define the field-to-column mapping.
+
Example configurations for `stocks_topic` to `stocks_table` using the minimum required settings:
+
[source,language-yaml]
---- 
tasks.max: 1
topics: stocks_topic
topic
  stocks_topic:
    stocks_keyspace:
      stocks_table:
        mapping: 'symbol=value.symbol, ts=value.ts, exchange=value.exchange, industry=value.industry, name=key, value=value.value'
----
