= DataStax Apache Pulsar™ Connector details
:page-aliases: cfgRefPulsarConnector.adoc
:page-tag: pulsar-connector,dev,develop,pulsar

Set the common DataStax Apache Pulsar™ Connector parameters.

== Parameters 

[source,language-yaml]
----
cloud.secureConnectBundle=/path/to/secure-connect-database_name.zip
----

[#secureConnectBundle]
cloud.secureConnectBundle:: The full path to the secure connect bundle for your DataStax Astra database (secure-connect-database_name.zip).
Download the secure connect bundle from the DataStax Cloud console.
+
If this option is specified, you must also include the auth.username and auth.password for the database user.
+
IMPORTANT: If you are using the cloud.secureConnectBundle, *ALL* subproperties under `ssl:` must be empty.


== Using a base64 encoded file

You can encode your zip file using the standard base64 tool, include it directly in the Pulsar configuration file, and the Pulsar function framework will take care of deploying it to additional Pulsar machines:

[source,language-bash]
----
base64 -i bundle.zip
----

Add the output of the command to `cloud.secureConnectBundle`:

[source,language-yaml]
----
cloud.secureConnectBundle=base64:UEsDBBQACAAIADmJJ1IAAAAAAAAAAAAAAAAGAAkAY2EuY3J0VVQFAAFeQPdfZJTJjvI4HMTveYq5t0bZoTl8Bzt2giEOOGQh3Mi+sgVw4qcf0a25zPj2L0s/VUml+vvzIHaI95eF/YDYxAIB/lElSgi2kGWBt1UBTiCoiAUvIUcs2WyvJ1K/Mw8w7EIGeHVmkyXABlZeBEESgD4KJMpGbrEERYwRzDeIBTikkDhADTGcqBtq9it3cMW0qc4GPOEA7H8B18DCfi3ljh3kjm1QZnAEfkAu5hFKnZV6QvaeYuUHBibPSTT8OsWblmqbJgm6pzfQWaKNo......
----
