= Internal or LDAP authentication
:page-aliases: cfgRefPulsarAuthLdap.adoc
:page-tag: pulsar-connector,security,secure,pulsar

When the cluster has internal or LDAP authentication enabled, configure the user name and password settings for DataStax Apache Pulsar™ Connector.
A login role for the connector with access to the mapped tables is also required.

[#ldap-parameters]
== Parameters

[source,language-yaml]
----
auth:
  provider: DSE
  username: login_role
  password: password
----

provider:: Select the type of authentication provider configured for the DataStax cluster.
-   **None** - No authentication.
-   **DSE** - Internal or LDAP authentication.
-   **GSSAPI** - Supports SASL authentication to DSE clusters using the GSSAPI mechanism \(Kerberos authentication\)
+
NOTE: When using GSSAPI, the Pulsar Connect process requires that the Kerberos configuration file `krb5.conf` location is provided in the `java.security.krb5.conf` system property at startup. See xref:internal-ldap-auth.adoc[].
+
Default: `None`

username:: DSE login role name or LDAP username.Astra database username.
+
NOTE: When [authorization is enabled](https://docs.datastax.comen/dse/6.8//dse-admin/datastax_enterprise/config/configDseYaml.html#configDseYaml__authorizationOptions), the DataStax connector login role must have a minimum of `modify` privileges on tables receiving data from the DataStax Apache Pulsar™ Connector.

password:: Login role or LDAP password.Astra database password for the specified username.
