= Removing a field map 
:page-aliases: opsPulsarRemoveField.adoc
:page-tag: pulsar-connector,dev,develop,pulsar

DataStax Apache Pulsar™ Connector processing fails if any mapped Pulsar topic fields are missing from the record.
If a field is missing or if the schema change is known ahead, remove the topic-column mapping.

WARNING: The database table schema has `PRIMARY KEY` columns that uniquely identify and partition rows.
See link:https://docs.datastax.com/en/dse/6.8/cql/cql/ddl/dataModelingCQLTOC.html[CQL data modeling].
A NULL is not allowed in a PRIMARY KEY column, therefore, each `PRIMARY KEY` column must have a field-column map.

. On a xref:index.adoc#supported-databases[supported database] node, use the CQLSH link:https://docs.datastax.com/en/dse/6.7/cql/cql/cql_reference/cqlsh_commands/cqlshDescribeTable.html[DESCRIBE TABLE] command to verify that the field is not a PRIMARY KEY (PK) column.
+
NOTE: If the field is a PK column, map a different field to the column.

. Remove the field to column mapping from the configuration. See xref:configure-map-topic-table.adoc[].
. Update the configuration with the new settings. See xref:update-config.adoc[].
. Start the Pulsar producer that had the schema change.
